# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "mgit-core",
    "mgit-cli",
    "mgit-gui",
]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
