[package]
name = "mgit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.8", features = ["derive", "cargo"] }
globset = { version = "0.4.9" }
walkdir = { version = "2.3.2" }
anyhow = { version = "1.0.65" }
serde = { version = "1.0.145", features = ["derive"] }
toml_edit = { version = "0.14.4", features = ["serde", "easy"]}
