[package]
name = "mgit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.65" }
clap = { version = "4.0.8", features = ["derive", "cargo"] }
git2 = { version = "0.15.0"}
globset = { version = "0.4.9" }
owo-colors = "3.5.0"
serde = { version = "1.0.145", features = ["derive"] }
toml = "0.5.9"
toml_edit = { version = "0.14.4", features = ["serde", "easy"]}
walkdir = { version = "2.3.2" }
assert_cmd = "2.0.4"

[dev-dependencies]
rand = "0.8.5"