version: "3.6"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    environment:
      - GITEA__APP__NAME=MGit
      - GITEA__security__IMPORT_LOCAL_PATHS=true
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__SECRET_KEY=mgit
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=mgit
      - GITEA__database__USER=mgit
      - GITEA__database__PASSWD=mgit
    restart: always
    networks:
      - gitea
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=mgit
      - POSTGRES_PASSWORD=mgit
      - POSTGRES_DB=mgit
    ports:
      - "5432:5432"
    networks:
      - gitea
