name: Rust
on:
  push:
    branches: [ "master" ]


env:
  CARGO_TERM_COLOR: always

jobs:
  test_cli:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04,  windows-2022, macos-11]
    steps:
    - uses: actions/checkout@v3
    - name: run mgit test
      run: cargo test -p mgit
